export const JOBS = [
  {
    id: '1',
    title: 'Front Desk Executive',
    morningShift: '5.30 AM - 2.00 PM',
    eveningShift: '2.00 PM - 11.00 PM',
    vacancies: 3,
    salary: '₹12,000 – ₹15,000 + Incentives',
    highlighted: true,
  },
  {
    id: '2',
    title: 'Manager',
    morningShift: '5.30 AM - 2.00 PM',
    eveningShift: '2.00 PM - 11.00 PM',
    vacancies: 1,
    salary: '₹25,000 + Incentives',
    highlighted: false,
  },
  {
    id: '3',
    title: 'Head Coach',
    morningShift: '5.30 AM - 2.00 PM',
    eveningShift: '2.00 PM - 11.00 PM',
    vacancies: 1,
    salary: '₹18,000 + Incentives',
    highlighted: false,
  },
  {
    id: '4',
    title: 'Senior Coach',
    morningShift: '5.30 AM - 2.00 PM',
    eveningShift: '2.00 PM - 11.00 PM',
    vacancies: 2,
    salary: '₹15,000 + Incentives',
    highlighted: false,
  },
  {
    id: '5',
    title: 'Trainer',
    morningShift: '5.30 AM - 2.00 PM',
    eveningShift: '2.00 PM - 11.00 PM',
    vacancies: 5,
    salary: '₹12,000 + Incentives',
    highlighted: false,
  },
];