export const PRODUCTS = [
  {
    id: '1',
    name: 'Whey Protein Powder',
    description: 'Supports muscle recovery and lean muscle growth.',
    price: 'Rs. 800',
    image: '/banner.png',
  },
  {
    id: '2',
    name: 'Pre-Workout Formula',
    description: 'Boosts energy, focus, and workout performance.',
    price: 'Rs. 1,800',
    image: '/banner.png',
  },
  {
    id: '3',
    name: 'Multivitamin Tablets',
    description: 'Daily nutrients to support overall health and immunity.',
    price: 'Rs. 500',
    image: '/banner.png',
  },
  {
    id: '4',
    name: 'Gym Training T-Shirt',
    description: 'Breathable fabric designed for intense workouts.',
    price: 'Rs. 400',
    image: '/banner.png',
  },
  {
    id: '5',
    name: 'Gym Jacket',
    description: 'Lightweight jacket for warm-ups and cool-downs.',
    price: 'Rs. 1,600',
    image: '/banner.png',
  },
  {
    id: '6',
    name: 'Gym Gloves',
    description: 'Improves grip and protects hands during lifts.',
    price: 'Rs. 800',
    image: '/banner.png',
  },
  {
    id: '7',
    name: 'Skipping Rope',
    description: 'Effective cardio tool for endurance and fat loss.',
    price: 'Rs. 200',
    image: '/banner.png',
  },
  {
    id: '8',
    name: 'Protein Shaker',
    description: 'Easy mixing for supplements on the go.',
    price: 'Rs. 250',
    image: '/banner.png',
  },
  {
    id: '9',
    name: 'Foam Roller',
    description: 'Helps reduce muscle soreness and improve mobility.',
    price: 'Rs. 500',
    image: '/banner.png',
  },
];
